### ISSUE TITLE
Windows 8.1 Compatibility

### ISSUE THREAD

**Issue by geekdave** [TestArmada/boilerplate-nightwatch#4]
Couldn't get `npm install` to work on an Windows 8.1 VM, due to:

Note, it was necessary to install python to get past a previous build error.

![image](https://cloud.githubusercontent.com/assets/1438478/8895965/23ba8d7a-33aa-11e5-81ba-34292d3d6796.png)

**Comment by asunar** [comment]
I guess I put my tips in the wrong repo. This is how I got the npm install to work.
https://github.com/TestArmada/testarmada.github.io/issues/2

I have VS 2013 on my machine(msvs_version flag). Otherwise, there is some info about installing node-gyp on Windows here.
https://github.com/TooTallNate/node-gyp

**Comment by Maciek416** [comment]
@asunar thanks for these tips. Looks like we've got some paths to fix up

**Comment by asunar** [comment]
Windows 8.1
$ node --version
v4.2.1
$ npm --version
3.3.9

Issues and workarounds
1. npm install fails => install Python 2.7, npm install --msvs_version 2015 (see Compiling Native Addon Modules at https://github.com/Microsoft/nodejs-guidelines/blob/master/windows-environment.md#configuring-your-windows-development-environment)
2. npm install succeeds but following files listed in ./conf/nightwatch.json do not exist.
- ./node_modules/testarmada-magellan-nightwatch/node_modules/selenium-server/lib/runner/selenium-server-standalone-2.46.0.jar
- ./node_modules/testarmada-magellan-nightwatch/node_modules/chromedriver/lib/chromedriver/chromedriver.exe (add the .exe extension)
- Download and place the files listed above in the correct locations.
- Run "./node_modules/.bin/magellan" --serial --browser=chrome (note the double quotes)

The tests should succeed (works on my machine).

============= Suite Complete =============

Status: PASSED
Runtime: 35.7s
Total tests: 2
Successful: 2 / 2

**Comment by asunar** [comment]
Windows 8.1
$ node --version
v4.2.1
$ npm --version
3.3.9

After creating the missing phantomjs file in the correct location (as listed in the ./conf/nightwatch.json file and adding the .exe to the end of the path) ran
 "./node_modules/.bin/magellan" --serial --browser=phantomjs

walmart test succeeds.

github test fails with the following error:
errorMessage\":\"Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: \\"script-src assets-cdn.github.com\\
